# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      if: matrix.os == 'ubuntu-latest'
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: '3.10'

    - name: Set up CMake for Windows
      if: matrix.os == 'windows-latest'
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build with CMake (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build .

    - name: Build with CMake (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        mkdir build
        cd build
        cmake -G "Visual Studio 16 2019" ..
        cmake --build . --config Release
